# Generated by Django 3.0.4 on 2020-07-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0002_auto_20200619_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_abnormal_current',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_abnormal_current_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_component_derating',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_component_derating_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_configuration',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_configuration_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_delta_bom',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_delta_bom_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_hardware_design',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_hardware_design_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_interface',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_interface_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_responsible',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_schematics',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_schematics_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='circuit_time',
            field=models.CharField(blank=True, default='0', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='comp_change_request',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='comp_change_request_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='comp_delta',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='comp_delta_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='comp_responsible',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='comp_updated',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='comp_updated_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='emc_equipment_test_plan',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='emc_equipment_test_plan_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='emc_equipment_test_reports',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='emc_equipment_test_reports_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='emc_existing_deviations',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='emc_existing_deviations_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='emc_responsible',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='emc_time',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='emc_vehicle_test',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='emc_vehicle_test_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='enviro_mounting',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='enviro_mounting_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='enviro_reliability',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='enviro_reliability_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='enviro_responsible',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='enviro_test_reports',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='enviro_test_reports_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='enviro_time',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='process_cutting_edge',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='process_cutting_edge_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='process_off_tool',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='process_off_tool_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='process_peses',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='process_peses_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='process_qualification_review',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='process_qualification_review_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='process_responsible',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='process_spp_activities',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='process_spp_activities_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='process_support_activities',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='process_support_activities_status',
            field=models.CharField(blank=True, default='Not Complete', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='process_time',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slm_request_ok',
            name='slm_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
